# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(max_length=100)),
                ('complaint_description', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('city_boarded', models.CharField(max_length=50)),
                ('city_arrival', models.CharField(max_length=50)),
                ('gateno', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FlightStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('city_boarded', models.CharField(max_length=50)),
                ('city_departed', models.CharField(max_length=50)),
                ('gateno', models.CharField(max_length=50)),
                ('update', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('linked_pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.FlightStatus')),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat1', models.CharField(max_length=50)),
                ('cat2', models.CharField(max_length=50)),
                ('cat3', models.CharField(max_length=50)),
                ('cat4', models.CharField(max_length=50)),
                ('cat5', models.CharField(max_length=50)),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.FlightStatus')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('twitter_name', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
                ('loyality_pts', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='preferences',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User'),
        ),
        migrations.AddField(
            model_name='location',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User'),
        ),
        migrations.AddField(
            model_name='flightstatus',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='linked_pnr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.FlightStatus'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User'),
        ),
    ]
