# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='linked_pnr',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.FlightStatus'),
        ),
        migrations.AlterField(
            model_name='location',
            name='user_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User'),
        ),
    ]
