# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0003_auto_20171004_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightstatus',
            old_name='pnr',
            new_name='flightno',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='update',
        ),
    ]
