# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0004_auto_20171004_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_date', models.DateTimeField()),
                ('from_loc', models.CharField(max_length=100)),
                ('to_loc', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('linked_no', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.FlightStatus')),
                ('user_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.User')),
            ],
        ),
    ]
