# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0005_myflights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myflights',
            name='linked_no',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='trend_promotion.Flight'),
        ),
    ]
