# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0007_auto_20171006_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pref',
            name='pnr',
        ),
    ]
