# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0008_remove_pref_pnr'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExistingOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flightno', models.CharField(max_length=50)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('city_boarded', models.CharField(max_length=50)),
                ('city_arrival', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PotentialOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('city_boarded', models.CharField(max_length=50)),
                ('city_arrival', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('twitter_name', models.CharField(max_length=50)),
                ('current_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='linked_pnr',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='pref',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
        migrations.DeleteModel(
            name='pref',
        ),
    ]
