# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0011_auto_20171007_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='potentialoffers',
            name='counter',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
