# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trend_promotion', '0012_auto_20171007_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tusers',
            old_name='email',
            new_name='temail',
        ),
    ]
